---
- name: "apt upgrade"
  apt: upgrade=full autoremove=yes update_cache=yes
- name: "common apt packages"
  apt:
    update_cache: yes
    pkg:
      - vim
      - byobu
      - htop
      - sysstat
      - tree
      - pv
      - jq
      - ntp
      - mosh
      - dstat
      - python3-pip
      - docker.io
      - iptables-persistent
- name: PyPI packages
  pip:
    name:
      - awscli
      - gsutil
      - azure-cli
      - docker
- name: sshd keepalive
  lineinfile: dest=/etc/ssh/sshd_config line="{{ item }}"
  loop:
    - ClientAliveInterval 60
    - ClientAliveCountMax 5
- name: user wdler
  user:
    name: wdler
    shell: /bin/bash
    uid: 1337
    groups: docker
    comment: Wid L. Hacker
- name: wdler SSH key
  authorized_key: user=wdler key="{{ lookup('file', public_key_path) }}"
- name: wlder sudoers
  lineinfile:
    dest: /etc/sudoers.d/50-wdler
    line: wdler ALL=(ALL) NOPASSWD:ALL
    create: yes
    owner: root
    group: root
    mode: 0440
- name: wdler nofile
  pam_limits:
    domain: wdler
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 1048576
  loop:
    - hard
    - soft
- name: wdler TMPDIR
  lineinfile: dest=/home/wdler/.profile line="export TMPDIR=/mnt/scratch/tmp"
  remote_user: wdler
  become: no
