---
- hosts: all
  become: yes
  roles:
    - aws_fsx_lustre_client
- hosts: all
  become: yes
  vars:
    - miniwdl_branch: mlin-cloud-prototype
  roles:
    - miniwdl
- hosts: all
  become: yes
  roles:
    - aws_docker_firewall
- hosts: all
  become: yes
  roles:
    - manager
