name: validate

on:
  push:
    branches:
      - test-aws
  pull_request:
    branches:
      - test-aws

jobs:
  swarm:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 0.12.24
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_PROFILE: aws-test
      AWS_DEFAULT_REGION: us-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    steps:
    - uses: actions/checkout@v2

    - name: generate ~/.aws/config
      # we don't use the official AWS Credentials Action because it needs the TagSession power
      run: |
        mkdir -p ~/.aws
        echo -e "[profile aws-test]\nrole_arn = $AWS_ROLE_TO_ASSUME\ncredential_source = Environment" >> ~/.aws/config
        >&2 cat ~/.aws/config

    - name: verify AWS credentials
      run: aws s3 ls s3://czi.miniwdl-test/
