name: test-aws

on:
  push:
    branches:
      - test-aws
  pull_request:
    branches:
      - test-aws

jobs:
  swarm:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 0.12.24
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      _AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      _AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_PROFILE: aws-test

    steps:
    - uses: actions/checkout@v2

    - name: generate ~/.aws/config
      # we don't use the official AWS Credentials Action because it needs the TagSession power
      run: |
        mkdir -p ~/.aws
        echo -e "[default]\nregion = us-west-2\n[profile aws-test]\nrole_arn = ${AWS_ROLE_TO_ASSUME}\nsource_profile = default" > ~/.aws/config
        echo -e "[default]\naws_access_key_id = ${_AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${_AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials

    - name: verify AWS credentials
      run: |
        >&2 cat ~/.aws/config
        aws s3 ls s3://czi.miniwdl-test/ --debug
