name: validate

on:
  push:
    branches:
      - test-aws
  pull_request:
    branches:
      - test-aws

jobs:
  swarm:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 0.12.24
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_DEFAULT_REGION: us-west-2

    steps:
    - uses: actions/checkout@v2

    - name: verify AWS credentials
      run: aws s3 ls s3://czi.miniwdl-test/
